name: linter
on: 
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install poetry
      run: pip install poetry
    - name: install dependancies
      run: make install
    - name: run linter
      run: make lint
 

