name: make_lint
on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        # make depends on poetry
    - name: Install dependencies
      run: |
          pip install poetry
          make install
    - name: install
      run: make install
    - name: build
      run: make build
    - name:  publish
      run: make publish
    - name: package-install
      run: make package-install
    - name: run linter
      run: make lint
 

