name: make_lint
on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install poetry
    - name: install
      run: make install
    - name: build
      run: make build
    - name:  publish
      run: make publish
    - name: package-install
      run: make package-install
    - name: run linter
      run: make lint
 

