name: make_lint
on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2   
    - name: run linter
      run: make lint
 

